version: '3.11'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    volumes:
      - ./data/elastic:/var/lib/elasticsearch/data
    environment:
      - discovery.type=single-node
    mem_limit: 2g

  django:
    build: .
    container_name: django2
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    environment:
      - DJANGO_DB_USER=$db_user
      - DJANGO_DB_PASSWORD=$db_password
      - DJANGO_DB_HOST=$db_host
      - DJANGO_DB_PORT=$db_port
      - DJANGO_DB_NAME=$db_name
    volumes:
      - .:/app
      - media_volume:/home/user/PythonMain/DRF_JWT/P15-turbosquid-backend/media
    depends_on:
      - database
      - elasticsearch
      - celery
      - redis

  database:
    image: postgres:15.3-alpine
    container_name: database
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=$db_name
      - POSTGRES_USER=$db_user
      - POSTGRES_PASSWORD=$db_password
      - POSTGRES_HOST=$db_host
      - POSTGRES_PORT=$db_port

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data/
    expose:
      - 6379

  celery:
    build: .
    command: celery -A P15turbosquid worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    mem_limit: 2g
volumes:
  media_volume:
  postgres_data:
  redis_data: