# Generated by Django 4.2.7 on 2023-11-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_products_slug_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='amount',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
