# Generated by Django 4.2.7 on 2023-11-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_shoppingcart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
