# Generated by Django 4.2.7 on 2023-11-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
    ]
