# Generated by Django 4.2.7 on 2023-11-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_shoppingcart_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='product_id',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
