# Generated by Django 4.2.7 on 2023-11-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_shoppingcart_product_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoppingcart',
            new_name='ShoppingCartt',
        ),
    ]
