# Generated by Django 4.2.7 on 2023-11-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_shopcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shopcart',
        ),
        migrations.RenameField(
            model_name='shoppingcartt',
            old_name='user',
            new_name='user_id',
        ),
    ]
