# Generated by Django 4.2.7 on 2023-11-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_shopcart_rename_user_shoppingcartt_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCartt',
            new_name='ShoppingCart',
        ),
    ]
