# Generated by Django 4.2.7 on 2023-11-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_shoppingcartt_shoppingcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
