# Generated by Django 4.2.7 on 2023-11-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_delete_shoppingcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=False)),
                ('user_id', models.IntegerField(default=False)),
            ],
        ),
    ]
