# Generated by Django 4.2.7 on 2023-11-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_category_delete_sectionsbytype_products_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='sections',
            name='parent',
        ),
    ]
