# Generated by Django 4.2.7 on 2023-11-16 12:04

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sections'),
        ),
    ]
